version: '2'

services:
  keycloak:
     hostname: keycloak
     image: jboss/keycloak:3.4.0.Final
     image: jboss/keycloak:14.0.0
     restart: always
     env_file:
       - keycloak_default_env
       - keycloak_secrets
     environment:
       - PROXY_ADDRESS_FORWARDING=true
       - _JAVA_OPTIONS=-Xmx256m -Xms64m
     #ports:
      # - "8080:8080"
      # - "10098:9990"
      # - "10099:8443"
     networks:
       - infra

networks:
  infra:
    external:
      name: staging_infra_default
