version: '3'

services:
  solr:
    image: solr:8.2.0
    restart: always
    command: "-cloud"
#    ports:
#      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/
    networks:
      - infra

volumes:
  solr_data:

networks:
  infra:
    external:
      name: staging_infra_default
