version: '2'

services:
  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./headers.js:/etc/nginx/headers.js:ro
      - ./certs:/etc/certs:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
    ports:
      - "80:80"
      - "8443:8443"
      - "443:443"
      #- "5601:5601"
    networks:
      - staging-infra
      - jenkins


networks:
  staging-infra:
    external:
      name: staging_infra_default
  jenkins:
    external:
      name: jenkins_default
