version: '2'

services:
  jenkins_master:
    image: nimbleplatform/jenkins-master:latest
    restart: always
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins.war:/usr/share/jenkins/jenkins.war:ro
      - root.ssh.dir:/root/.ssh 
      - ${DEPLOY_HOME}/.ssh/id_rsa:/root/.ssh/id_rsa # set in env-variable .env file
      - ${SSH_CONFIG_FILE}:/root/.ssh/config # needs correct owner and permissions
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS="--prefix=/jenkins/"
      - JAVA_OPTS="-Dhudson.model.DownloadService.noSignatureCheck=true"
#    ports:
#      - "50000:50000"
    networks:
      - jenkins


networks:
  jenkins:
    external:
      name: jenkins_default

volumes:
  root.ssh.dir: {}