version: '3'

services:
  ##########################
  #### MS Infrastructure ###
  ##########################

  config-server:
    hostname: config-server
    image: nimbleplatform/config-server:latest
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms50m
    networks:
      - infra

  service-discovery:
    hostname: service-discovery
    image: nimbleplatform/service-discovery:latest
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms50m
    depends_on:
      - config-server
    networks:
      - infra

  gateway-proxy:
    hostname: gateway-proxy
    image: nimbleplatform/gateway-proxy:latest
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
      - env_vars-gateway-proxy
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms50m
    depends_on:
      - config-server
      - service-discovery
    networks:
      - infra


  ########################
  ###### Database ########
  ########################

  staging-main-db:
    image: postgres:10
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
    volumes:
      - ./initdb/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql:ro
      - staging-main-db:/var/lib/postgresql/data
    networks:
      - infra

  ##############################
  ######## Apache Kafka ########
  # (req. by identity-service) #
  ##############################

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092 #,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT #,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # as long as we have just one broker
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    #volumes:
    #  - ./zk-multiple-kafka-multiple/kafka1/data:/var/lib/kafka/data
    networks:
      - infra
    depends_on:
      - zoo1

  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    restart: always
    ports:
      - "2181:2181"
    networks:
      - infra

volumes:
  staging-main-db:

networks:
  infra:
    external:
      name: staging_infra_default
