version: '3'

services:
  ##########################
  #### MS Infrastructure ###
  ##########################

  config-server:
    hostname: config-server
    image: nimbleplatform/config-server:latest
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms50m
    networks:
      - infra

  service-discovery:
    hostname: service-discovery
    image: nimbleplatform/service-discovery:latest
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms50m
    depends_on:
      - config-server
    networks:
      - infra

  gateway-proxy:
    hostname: gateway-proxy
    image: nimbleplatform/gateway-proxy:latest
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms50m
    depends_on:
      - config-server
      - service-discovery
    networks:
      - infra


  ########################
  ###### Database ########
  ########################

  staging-main-db:
    image: postgres:10
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/
      - staging-main-db:/var/lib/postgresql/data
    networks:
      - infra

volumes:
  staging-main-db:

networks:
  infra:
    external:
      name: staging_infra_default
