version: '3'

services:
  ##########################
  #### MS Infrastructure ###
  ##########################

  config-server:
    hostname: config-server
    image: nimbleplatform/config-server:latest
    env_file:
      - env_vars
    ports:
      - "8888:8888"
    environment:
      _JAVA_OPTIONS: -Xmx128m -Xms50m
    networks:
      - infra

  service-discovery:
    hostname: service-discovery
    image: nimbleplatform/service-discovery:latest
    env_file:
      - env_vars
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      _JAVA_OPTIONS: -Xmx128m -Xms50m
    networks:
      - infra

  gateway-proxy:
    hostname: gateway-proxy
    image: nimbleplatform/gateway-proxy:latest
    env_file:
      - env_vars
    ports:
      - "80:80"
    depends_on:
      - config-server
      - service-discovery
    environment:
      _JAVA_OPTIONS: -Xmx128m -Xms50m
    networks:
      - infra

  ##########################
  ######## Keycloak ########
  ##########################

  keycloak:
    hostname: keycloak
    build: ./keycloak
    environment:
      KEYCLOAK_LOGLEVEL: DEBUG
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      POSTGRES_DATABASE: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_PORT_5432_TCP_ADDR: keycloak-db
      PROXY_ADDRESS_FORWARDING: "true"
      _JAVA_OPTIONS: -Xmx128m -Xms50m
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/migration/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    ports:
      - "8080:8080"
      # - "9999:9999" # keycloak federation port - not used in local dev setup
      - "8443:8443"
    volumes:
      - ./keycloak/init-migration/:/migration/
    links:
      - keycloak-db:postgres
    depends_on:
      - keycloak-db
    networks:
      - infra
      - keycloak

  keycloak-db:
    image: postgres:10
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_ROOT_PASSWORD: root_password
    networks:
      - keycloak

  ##############################
  ##### SMTP Email service #####
  ##############################

  maildev:
    hostname: maildev
    image: djfarrelly/maildev:0.14.0
    ports:
      - "8025:80"
    networks:
      - infra

  ##############################
  ###### SOLR service ##########
  ##############################
  
  solr:
    hostname: solr
    image: solr:7.6.0
    command: "-cloud"
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/
    networks:
      - infra

  ##############################
  ######## Apache Kafka ########
  # (req. by identity-service) #
  ##############################

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092 #,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT #,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # as long as we have just one broker
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    #volumes:
    #  - ./zk-multiple-kafka-multiple/kafka1/data:/var/lib/kafka/data
    networks:
      - infra
    depends_on:
      - zoo1

  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    networks:
      - infra

  ##############################
  ###### Local database ########
  ##############################

  dev-main-db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/
      - dev-main-db:/var/lib/postgresql/data
    networks:
      - infra

volumes:
  keycloak_postgres_data:
  solr_data:
  dev-main-db:

networks:
  infra:
    external:
      name: dev_infra_default
  keycloak:
